[package]
name = "impex"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", optional = true }

[dev-dependencies]
impex = { path = ".", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
