[package]
name = "impex"
version = "0.1.0"
edition = "2024"
description = "Implicit/Explicit struct fields for serde serialization"
readme = "README.md"
license = "MIT"
repository = "https://github.com/mineichen/impex"

[dependencies]
serde = { version = "1" }
impex-derive = { path = "../impex-derive", version = "0.1.0", optional = true }


[features]
default = ["derive"]
visitor = ["impex-derive?/visitor"]
derive = ["dep:impex-derive", "serde/derive"]

[dev-dependencies]
impex = { path = ".", features = ["visitor"] }
serde_json = "1"
